---
name: Deploy AWS Infrastructure

"on":
  push:
    branches:
      - main

env:
  REGION: ${{ secrets.AWS_REGION }}
  BUCKET_NAME: ${{ secrets.AWS_BUCKET }}
  AWS_WEB_ROLE: ${{ secrets.AWS_WEB_ROLE }}
  DEST_PATH: code/customer_analytics
  WHEEL_FILE_NAME: event_driven_cpssw-0.1.0-py3-none-any.whl

jobs:
  deploy_glue_jobs:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        glue:
          - bootstrap/iceberg_migration
          - bronze/ingest_customers
          - bronze/ingest_products
          - bronze/ingest_sale_orders
          - bronze/ingest_suppliers
          - bronze/ingest_warehouses
          - silver/silver_dimension_customers
          - silver/silver_dimension_products
          - silver/silver_dimension_suppliers
          - silver/silver_dimension_warehouses
          - silver/silver_fact_sale_orders
          - gold/gold_summary_reports

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_WEB_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Deploy Glue Job - ${{ matrix.glue }}
        run: |
          JOB_NAME=$(basename "${{ matrix.glue }}")
          python infrastructure/create_glue_jobs.py ${JOB_NAME} \
          $AWS_WEB_ROLE \
          s3://$BUCKET_NAME/warehouse/event-driven-cpssw-artifacts/glue-scripts/${{ matrix.glue }}.py \
          $BUCKET_NAME \
          s3://$BUCKET_NAME/warehouse/event-driven-cpssw-artifacts/dist/$WHEEL_FILE_NAME
